# Generated by Django 3.1.4 on 2021-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awali_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
