# Generated by Django 3.1.4 on 2021-05-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awali_admin', '0002_auto_20210531_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
