# Generated by Django 3.1.4 on 2021-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awali_admin', '0003_invoiceitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
