# Generated by Django 3.1.4 on 2021-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awali_admin', '0003_auto_20210531_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
