# Generated by Django 3.1.4 on 2021-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awali_admin', '0004_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
