# Generated by Django 3.1.4 on 2021-05-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awali_admin', '0005_auto_20210531_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='Invoice',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='customer_sale_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
